### ISSUE TITLE
Scoreboards teams bug

### ISSUE THREAD

**Issue by CleusGamer201** [JitseB/NPCLib#15]
`11:49:53 [INFORMACIÓN] [CleusGamer201] <-> ServerConnector [Lobby] has connected
11:50:08 [GRAVE] [CleusGamer201] <-> DownstreamBridge <-> [Lobby] - encountered exception
java.lang.IllegalArgumentException: Team 09e2bc9b88 already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
	at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:206)
	at net.md_5.bungee.protocol.packet.Team.handle(Team.java:122)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at java.lang.Thread.run(Unknown Source)
11:50:08 [INFORMACIÓN] [CleusGamer201] disconnected with: §fIllegalArgumentException : Team 09e2bc9b88 already exists in this scoreboard @ com.google.common.base.Preconditions:191` #I' have conected after it, 18 minutes later kicked me again with the same errror

I'm using Spigot-1.8.8 with BungeeCord Last Build,

Some times when you are left from the range vision and goes to the npc kick the player with this exception. And when i used npc.show(player, true); the npc do not appears and the player is in the range vision

PD: Sorry for my bad english!

**Comment by JitseB** [comment]
Are you using `NPC#show(player, true/false)`? You're not supposed to utilise this method, nor should you use `NPC#hide(player, true/false)`. These are methods used by the internal system. NPCs should (under normal circumstances) hide and show automatically.

**Comment by CleusGamer201** [comment]
the npcs do not appears/dissappears if i don't use `NPC#show` for `NPC#hide`

**Comment by CleusGamer201** [comment]
i will try again later,...

**Comment by CleusGamer201** [comment]
I have tried but the npc does not appear / disappear if I do not use the method manually.

**Comment by JitseB** [comment]
Could you give a snippet of the code you're using the spawn (and show) the NPCs?

This issue is not a bug

**Comment by CleusGamer201** [comment]
Hello, here some part of my code,

public class NpcManager implements Listener {
	
    private List<CustomNPC> npcs;
    private final NPCLib library;
    private Skin shopSkin, soloSkin, doubleSkin;
    private List<String> holoText = Utils.color(Arrays.asList("&d&lHOLOGRAM &f&l- &c&l%s", "&7(Right Click)"));
    
    public NpcManager() {
        this.npcs = new ArrayList<CustomNPC>();
        this.library = new NPCLib(Main.getMain());
        Bukkit.getPluginManager().registerEvents(this, Main.getMain());
    }
    
    public void setup() {
        this.npcs.clear();
        Utils.log("&eLoading NPCs....");
        MineSkinFetcher.fetchSkinFromIdAsync(54948, skin -> this.shopSkin = skin);
        MineSkinFetcher.fetchSkinFromIdAsync(60474, skin -> this.soloSkin = skin);
        MineSkinFetcher.fetchSkinFromIdAsync(78960, skin -> this.doubleSkin = skin);
        
        if (!Main.getMain().config.isConfigurationSection("NPCs"))
    		return;
    	
        Bukkit.getScheduler().runTaskLater(Main.getMain(), () -> {
        	for (String key : Main.getMain().config.getConfigurationSection("NPCs").getKeys(false)) {
    			final Location loc = Utils.locFromString(Main.getMain().config.getString("NPCs." + key + ".loc"));
    			String mode = Main.getMain().config.getString("NPCs." + key + ".mode");
    			
    			CustomNPC npc;
    			if (mode.equals("SHOP")) {
    				npc = addNPC(loc).getNPC();
    				Main.getMain().config.set("NPCs." + key + ".id", npc.getEntityId());
    				continue;
    			}
    			
    			npc = addNPC(loc, GameMode.valueOf(mode)).getNPC();
    			Main.getMain().config.set("NPCs." + key + ".id", npc.getEntityId());
    		}
        	Utils.log("&eLoaded " + this.npcs.size() + " NPC(s)");
            Main.getMain().config.save();
            Main.getMain().config.reload();
        }, 60L);
    }

@EventHandler
    public void onJoin(PlayerJoinEvent e) {
    	final Player p = e.getPlayer();
    	for (CustomNPC npc : npcs) {
    		if (!npc.getNPC().isActuallyShown(p))
    			npc.getNPC().show(p);
    	}
    }
    
    @EventHandler
    public void onQuit(PlayerQuitEvent e) {
    	final Player p = e.getPlayer();
    	for (CustomNPC npc : npcs) {
    		if (npc.getNPC().isActuallyShown(p))
    			npc.getNPC().hide(p);
    	}
    }
`

It works good, but some times when the player click the pc or walk to the npc got kicked by a error similar to this Team 09e2bc9b88 already exists in this scoreboar #Thanks and sorry for the wait!

**Comment by JitseB** [comment]
First of all, you shouldn't use `NPC#isActuallyShown`, that's an internally used method.

One way to generate this error is by not correctly shutting down a server (i.e. terminating the process). If this is something you have done, it's necessary for you to delete the scoreboard file in your world folder.

I'll take a look if I can add an extra check so this will generate a warning in a future version of NPCLib.

**Comment by CleusGamer201** [comment]
oh, Thanks. Sorry for the incovenience.
