### ISSUE TITLE
Nullpointer when creating NPC

### ISSUE THREAD

**Issue by HorizonCode** [JitseB/NPCLib#170]
**Describe the bug**
NullPointer when invoking `npcLib.createNPC()`

**NPCLib usage option**
shading the lib via gradle into my project

**NPCLib JAR name**
i tried npclib 2.11.1 and 2.12.1

**Server version**
CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**To Reproduce**
Code: 
```java Location loc = player.getLocation();
        NPC npc = npcLib.createNPC();
        npc.setLocation(loc);
        npc.create();
        npc.show(player);
```

Error:
```[08:58:46 WARN]: NPCLib Failed to create NPC. Please report the following stacktrace message
java.lang.NullPointerException
	at net.jitse.npclib.NPCLib.createNPC(NPCLib.java:114) [HNCP-Core-1.0.jar:?]
	at net.jitse.npclib.NPCLib.createNPC(NPCLib.java:128) [HNCP-Core-1.0.jar:?]
	at net.hncpteam.core.events.PlayerEvents.onJoin(PlayerEvents.java:132) [HNCP-Core-1.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

**Comment by HorizonCode** [comment]
Update: i just imported the 1.8R3 NMS Package and it works now.

`compile group: 'net.jitse', name: 'npclib-nms-v1_8_R3', version: '2.11.1-SNAPSHOT'`
