### ISSUE TITLE
Failed load the plugin

### ISSUE THREAD

**Issue by Angxstupst** [JitseB/NPCLib#174]
When I try the  start the plugin comes this error:

```xml Could not load 'plugins\NPCTest.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: NPCLib
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]```

**Comment by Angxstupst** [comment]
I fix this problem
