### ISSUE TITLE
Error on Create

### ISSUE THREAD

**Issue by EazyFTW** [JitseB/NPCLib#29]
**Describe the bug**
It is saying that the class doesn't exist.

**NPCLib usage option**
1

**NPCLib JAR name**
npclib-plugin-2.0.1-SNAPSHOT.jar

**Server version**
Paper version git-Paper-641 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
You are running the latest version

**To Reproduce**
Create an NPC using the Lib.

**Expected behavior**
It would create the npc w/ no errors.

**Screenshots**
```
[06:14:04 WARN]: Exception in thread "Thread-51" java.lang.NoSuchMethodError: net.jitse.npclib.NPCLib.createNPC(Ljava/util/List;)Lnet/jitse/npclib/api/NPC;
[06:14:04 WARN]: at net.vast.pvp.modules.npc.DJCreepz.lambda$onEnable$1(DJCreepz.java:31)
[06:14:04 WARN]: at net.jitse.npclib.api.skin.MineSkinFetcher.lambda$fetchSkinFromIdAsync$0(MineSkinFetcher.java:47)
[06:14:04 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by EazyFTW** [comment]
I saw https://github.com/JitseB/NPCLib/issues/28 and saw that, so I tried the plugin, instead of the api, but that didn't work either. I'm probs doing something wrong, idk.

**Comment by EazyFTW** [comment]
I was looking at the examples too, I basically did the same thing, besides.. what is ids? https://github.com/JitseB/NPCLib/blob/master/examples/example-3.java#L42

**Comment by JitseB** [comment]
Strange issue. NPCLib does indeed load all NMS classes corresponding to your server’s version...

Could you post a snippet of the code you’re using to create the NPC?

**Comment by EazyFTW** [comment]
```
        npclib = new NPCLib(VastPvP.getInstance());
        MineSkinFetcher.fetchSkinFromIdAsync(1132172857, skin -> {
            npc = npclib.createNPC(Arrays.asList(new Message("&a&lDJ Creepz").getColored(), new Message("&7How's it Creepin?").getColored(), new Message("&7Ready to get your").getColored(), new Message("&7groove on?").getColored()))
                    .setSkin(skin)
                    .setLocation(new Location(Bukkit.getWorld("world"), 5.5, 183, -6.5, 42, 0))
                    .create();
            Bukkit.getScheduler().runTask(VastPvP.getInstance(), () -> {
                for(Player p : Bukkit.getOnlinePlayers()) npc.show(p);
            });
        });
```

**Comment by EazyFTW** [comment]
If it helps i'm using my own API, I export (extract) the plugin (npclib-plugin) into the api (Using IntelliJ's Compile), and then I add the api via gradle. My api is built in maven, and plugin in gradle.

**Comment by termxz** [comment]
I replicated the issue and no errors appeared. I believe the issue is related to how you build your plugin and stuff. Have you checked to see if your compiled plugin contains the NPCLib class(as well as everything that comes with it)?

**Comment by JitseB** [comment]
> I replicated the issue and no errors appeared. I believe the issue is related to how you build your plugin and stuff. Have you checked to see if your compiled plugin contains the NPCLib class(as well as everything that comes with it)?

I've double checked and NPCLib does indeed package everything correctly.

Any chance you're using `minimizeJar` in your pom.xml build settings?

**Comment by EazyFTW** [comment]
I don't believe I am. Everything worked fine before 2.0.

**Comment by EazyFTW** [comment]
So, I tried removing it from my api, and directly shadowing it via gradle, and that didn't do anything.
