### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by andrei923** [JitseB/NPCLib#37]
**NPCLib usage option**
1

**NPCLib JAR name**
npclib-plugin-2.0.1-SNAPSHOT.jar

**Server version**
Spigot 1.8.8

**To Reproduce**
```
private NPCLib library;

@Override
public void onEnable() {
    this.library = new NPCLib(this);
}
```

**Additional context**
```
[11:17:27 INFO]: [LeafSK] Enabling LeafSK v2.0.4
[11:17:27 INFO]: NPCLib Attempting to inject into netty
[11:17:27 ERROR]: Error occurred while enabling LeafSK v2.0.4 (Is it up to date?)
java.lang.RuntimeException: Cannot invoke method static java.util.List net.minecraft.server.v1_8_R3.ServerConnection.access$0(net.minecraft.server.v1_8_R3.ServerConnection)
        at com.comphenix.tinyprotocol.Reflection.lambda$getTypedMethod$0(Reflection.java:231) ~[?:?]
        at com.comphenix.tinyprotocol.TinyProtocol.registerChannelHandler(TinyProtocol.java:189) ~[?:?]
        at com.comphenix.tinyprotocol.TinyProtocol.<init>(TinyProtocol.java:86) ~[?:?]
        at net.jitse.npclib.listeners.PacketListener$1.<init>(PacketListener.java:43) ~[?:?]
        at net.jitse.npclib.listeners.PacketListener.start(PacketListener.java:43) ~[?:?]
        at net.jitse.npclib.NPCLib.<init>(NPCLib.java:53) ~[?:?]
        at com.leaf.Leaf.onEnable(Leaf.java:49) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[paper.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [paper.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [paper.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [paper.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [paper.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at com.comphenix.tinyprotocol.Reflection.lambda$getTypedMethod$0(Reflection.java:229) ~[?:?]
        ... 17 more
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_8_R3.ServerConnection.access$0(ServerConnection.java:63) ~[paper.jar:git-PaperSpigot-"4c7641d"]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at com.comphenix.tinyprotocol.Reflection.lambda$getTypedMethod$0(Reflection.java:229) ~[?:?]
        ... 17 more

```

**Comment by JitseB** [comment]
Seems to be an anomaly with the initialization of TinyProtocol. Were you able to reproduce this on multiple occasions?

**Comment by andrei923** [comment]
it always happens, here is the src https://github.com/andrei923/test

**Comment by JitseB** [comment]
I’m not exactly sure how you’re shading my plugin. The repository contains a pom file, why don’t you shade the NPCLib artifact that’s on OSSRH? Are you trying to use Jitpack?

**Comment by andrei923** [comment]
updated the pom, nothing changed.

**Comment by JitseB** [comment]
I cloned your test repository and have been unsuccessful in reproducing your error. Are you using a modified Spigot fork by any chance?

If not, you could try to rebuild your Spigot 1.8.8 JAR using BuildTools.

**Comment by andrei923** [comment]
> you could try to rebuild your Spigot 1.8.8 JAR using BuildTools.
did this now, nothing changed.

**Comment by JitseB** [comment]
I doubt this will work, but I have no idea where it could come from otherwise... try updating to 2.2-SNAPSHOT. It's the latest version I released a few hours ago.

**Comment by andrei923** [comment]
updated to 2.2, reinstalled java JDK, tried to build it with IntelliJ, nothing changed.

**Comment by JitseB** [comment]
This is strange for sure. 🤔

**Comment by JitseB** [comment]
Okay, what if you try one of my example classes. Try creating a plugin without the Skript dependency and it doesn't matter if it's a Maven project or an Eclipse/IntelliJ project (i.e. usage option).

**Comment by andrei923** [comment]
removed skript dependency, this in the main and only class
package com.leaf;

```
import net.jitse.npclib.NPCLib;
import org.bukkit.plugin.java.JavaPlugin;

public class Leaf extends JavaPlugin {
	public static Leaf plugin;
	private NPCLib library;

	public Leaf() {
		if (plugin != null)
			throw new IllegalStateException("LeafSK can't have two instances.");
		plugin = this;	
	}	
	@Override
	public void onEnable() {		
		this.library = new NPCLib(this);
		};
	public static Leaf getInstance(){
		return plugin;
	}		
	public NPCLib getNPCLib() {
	    return library;
	}	
}
```

**Comment by JitseB** [comment]
Similar behavior found on the SpigotMC forum: https://www.spigotmc.org/threads/protocollib.36230/page-35#post-1967655

**Comment by JitseB** [comment]
Hmm. What happens if you create a new server with the Spigot JAR and the plugin you wrote? Do you still get the error then?

At this point I'm just trying to help you debug. I'm sorry... 🙄

**Comment by andrei923** [comment]
deleting old server files made it work somehow, thanks a lot for your help.

**Comment by JitseB** [comment]
Ah, good to hear that.

Best of luck!
