### ISSUE TITLE
1.14.4 Support Problem

### ISSUE THREAD

**Issue by CleusGamer201** [JitseB/NPCLib#55]
**Describe the bug**
Clear and concise description is: The support for NPCLib in 1.14.4 using Spigot throws error. (They works correctly in 1.8.8 and 1.15.2 the hologram is a visible armorstand only) But my problem is the 1.14.4 error when load the library.

**NPCLib usage option**
Usage: 1

**NPCLib JAR name**
Lastest Jar.

**Server version**
server is running CraftBukkit version git-Spigot-56f8471-6567017 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Screenshots**
`[18:52:03] [Server thread/ERROR]: Error occurred while enabling KBFFA v4.0 (Is it up to date?)
java.lang.RuntimeException: Cannot invoke method static java.util.List net.minecraft.server.v1_14_R1.ServerConnection.access$0(net.minecraft.server.v1_14_R1.ServerConnection)
	at com.comphenix.tinyprotocol.Reflection.lambda$0(Reflection.java:231) ~[?:?]
	at com.comphenix.tinyprotocol.TinyProtocol.registerChannelHandler(TinyProtocol.java:183) ~[?:?]
	at com.comphenix.tinyprotocol.TinyProtocol.<init>(TinyProtocol.java:85) ~[?:?]
	at net.jitse.npclib.listeners.PacketListener$1.<init>(PacketListener.java:42) ~[?:?]
	at net.jitse.npclib.listeners.PacketListener.start(PacketListener.java:42) ~[?:?]
	at net.jitse.npclib.NPCLib.<init>(NPCLib.java:54) ~[?:?]
	at dev.cleusgamer201.kbffa.Main.listeners(Main.java:189) ~[?:?]
	at dev.cleusgamer201.kbffa.Main.onEnable(Main.java:89) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Server.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [Server.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [Server.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [Server.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [Server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [Server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [Server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776) [Server.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.invoke.MethodHandleImpl$BindCaller$T/20968219.invoke_V(Unknown Source) ~[?:?]
	at com.comphenix.tinyprotocol.Reflection.lambda$0(Reflection.java:229) ~[?:?]
	... 16 more
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_14_R1.ServerConnection.access$0(ServerConnection.java:41) ~[Server.jar:git-Spigot-9de398a-9c887d4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.invoke.MethodHandleImpl$BindCaller$T/20968219.invoke_V(Unknown Source) ~[?:?]
	at com.comphenix.tinyprotocol.Reflection.lambda$0(Reflection.java:229) ~[?:?]
	... 16 more`

**Comment by CleusGamer201** [comment]
Another problem is that ViaVersion kicks the player if try joining with 1.14.4 from spigot-1.8.8.jar This problem is from ViaVersion? Or Incompatibilies?

**Comment by JitseB** [comment]
I've seen some strange behavior of TinyProtocol before. I'll look into this.

**Comment by JitseB** [comment]
My latest commit should patch this issue. Please wait a bit, I'll release a new version of NPCLib in the upcoming days.
