### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Devathlon-1202** [JitseB/NPCLib#56]
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:528)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
	at net.minecraft.server.v1_8_R3.PlayerList.attemptLogin(PlayerList.java:506)
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:114)
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:50)
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:167)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1001)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:422)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:760)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:663)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38)
	at java.lang.reflect.Field.get(Field.java:393)
	at com.comphenix.tinyprotocol.Reflection$1.get(Reflection.java:153)
	at com.comphenix.tinyprotocol.TinyProtocol.getChannel(TinyProtocol.java:260)
	at com.comphenix.tinyprotocol.TinyProtocol.access$800(TinyProtocol.java:29)
	at com.comphenix.tinyprotocol.TinyProtocol$5.onPlayerLogin(TinyProtocol.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
	... 14 more

**Comment by Devathlon-1202** [comment]
Spigot: 1.8.8
NPCLib: 2.4-SNAPSHOT

**Comment by JitseB** [comment]
Could you please provide more information about the bug you're having?
I have posted an issue ticket format on the repo. Please use this next time.

How can this bug be reproduced?

**Comment by JitseB** [comment]
Closed due to inactivity. Ticket may be reopened at any time.
