### ISSUE TITLE
Unable to find constructure w/ JDK11-OpenJ9

### ISSUE THREAD

**Issue by RealGatt** [JitseB/NPCLib#59]
**Describe the bug**
Unable to create NPCs. Reflection is unable to locate the correct constructor.

**NPCLib usage option**
3

**NPCLib JAR name**
2.4.1 Plugin shaded into JAR

**Server version**
PaperSpigot-4c7641d (aka; paper-443 for 1.8.8)

**To Reproduce**
Create an NPC using any of the create methods.

**Expected behavior**
n/a

**Screenshots**
```
> [06:07:18 ERROR]: [ACF] Caused by: java.lang.IllegalStateException: Unable to find constructor for class net.minecraft.server.v1_8_R3.EntityArmorStand ([class net.minecraft.server.v1_8_R3.WorldServer]).
> [06:07:18 ERROR]: [ACF] at com.comphenix.tinyprotocol.Reflection.getConstructor(Reflection.java:279)
> [06:07:18 ERROR]: [ACF] at net.jitse.npclib.hologram.Hologram.createPackets(Hologram.java:117)
> [06:07:18 ERROR]: [ACF] at net.jitse.npclib.hologram.Hologram.<init>(Hologram.java:92)
> [06:07:18 ERROR]: [ACF] at net.jitse.npclib.nms.v1_8_R3.NPC_v1_8_R3.createPackets(NPC_v1_8_R3.java:39)
> [06:07:18 ERROR]: [ACF] at net.jitse.npclib.internal.NPCBase.create(NPCBase.java:132)
> [06:07:18 ERROR]: [ACF] at net.gravitas.gravitasapi.npcs.CustomNPC.build(CustomNPC.java:201)
```

**Additional context**
We're using Java 11-OpenJ9.
The issue also appeared on our 1.14.4 instances, but was fixed as it was a custom Spigot build, simply by adding a new constructure using `WorldServer` instead of `World` (see below).

```
    // custom constructure to allow NPCLib to correctly target a constructor
    public EntityArmorStand(WorldServer world, double d0, double d1, double d2) {
        this(EntityTypes.ARMOR_STAND, world);
        this.setPosition(d0, d1, d2);
    }

    public EntityArmorStand(World world, double d0, double d1, double d2) {
        this(EntityTypes.ARMOR_STAND, world);
        this.setPosition(d0, d1, d2);
    }
```

I expect this issue is due to Java 11 and the Reflection class not accepting superclasses as a valid option.

**Comment by RealGatt** [comment]
Upon further research, the issue seems to be due to [SlimeWorldManager](https://github.com/Grinderwolf/Slime-World-Manager) as it creates a new World object ( [example](https://github.com/Grinderwolf/Slime-World-Manager/blob/develop/slimeworldmanager-nms-v1_15_R1/src/main/java/com/grinderwolf/swm/nms/v1_15_R1/CustomWorldServer.java) )

Not sure if this is something that is fixable on your end.

**Comment by RealGatt** [comment]
I've forked NPCLib and attempted to fix it.

```
Reflection.ConstructorInvoker entityArmorStandConstructor = null;
        try{
            System.out.println("Method 1 Attempt " + worldClass.getName());
            entityArmorStandConstructor = (version.isAboveOrEqual(MinecraftVersion.V1_14_R1) ?
                    Reflection.getConstructor(ENTITY_ARMOR_STAND_CLAZZ, worldClass, double.class, double.class, double.class) :
                    Reflection.getConstructor(ENTITY_ARMOR_STAND_CLAZZ, worldClass));
            System.out.println("Method 1");
        }catch (Exception e){
            System.out.println("Method 1 Failed");
            try {
                worldClass = worldClass.getSuperclass();

                System.out.println("Method 2 Attempt " + worldClass.getName());

                entityArmorStandConstructor = (version.isAboveOrEqual(MinecraftVersion.V1_14_R1) ?
                        Reflection.getConstructor(ENTITY_ARMOR_STAND_CLAZZ, worldClass, double.class, double.class, double.class) :
                        Reflection.getConstructor(ENTITY_ARMOR_STAND_CLAZZ, worldClass));

                System.out.println("Method 2");
            }catch (Exception e2){

                System.out.println("Method 2 Failed");
                if (Bukkit.getPluginManager().getPlugin("SlimeWorldManager") != null){

                    try {
                        worldClass = Reflection.getUntypedClass("com.grinderwolf.swm.nms." + NPCLib.getVersionName() + ".CustomWorldServer");

                        worldClass = worldClass.getSuperclass().getSuperclass();

                        System.out.println("Method 3 Attempt " + worldClass.getName());

                        entityArmorStandConstructor = (version.isAboveOrEqual(MinecraftVersion.V1_14_R1) ?
                                Reflection.getConstructor(ENTITY_ARMOR_STAND_CLAZZ, worldClass, double.class, double.class, double.class) :
                                Reflection.getConstructor(ENTITY_ARMOR_STAND_CLAZZ, worldClass));

                        System.out.println("Method 3");
                    }catch (Exception e3){
                        System.out.println("Failing silently... or not");
                    }
                }
            }
        }
```

Using the following code I was able to get the NPCs' to spawn with SlimeWorldManager. The main portion of the code is getting the SuperClass of the `WorldServer` object thats retrieved.

```
        Reflection.ConstructorInvoker entityArmorStandConstructor = null;
        try{
            entityArmorStandConstructor = (version.isAboveOrEqual(MinecraftVersion.V1_14_R1) ?
                    Reflection.getConstructor(ENTITY_ARMOR_STAND_CLAZZ, worldClass, double.class, double.class, double.class) :
                    Reflection.getConstructor(ENTITY_ARMOR_STAND_CLAZZ, worldClass));
        }catch (Exception e){
            try {
                worldClass = worldClass.getSuperclass();

                entityArmorStandConstructor = (version.isAboveOrEqual(MinecraftVersion.V1_14_R1) ?
                        Reflection.getConstructor(ENTITY_ARMOR_STAND_CLAZZ, worldClass, double.class, double.class, double.class) :
                        Reflection.getConstructor(ENTITY_ARMOR_STAND_CLAZZ, worldClass));
}
```

Should fix the issue.

Now I'm getting a new issue with non 1.8 clients on a 1.8 server; they get kicked with an `ArrayIndexOutOfBoundsException: 6` error.

Currently investigating that issue.

**Comment by JitseB** [comment]
I'll see what I can do about this. With your fix it should be the same issue as found in #58.
Are you using any sort of server proxy? E.g. BungeeCord?

**Comment by RealGatt** [comment]
We're running Waterfall w/ ViaVersion on the Proxy & locally on the 1.8 servers.

If you go onto the server w/ a 1.8 client it works fine, but on any other version it crashes with that error. I don't know enough about packets to properly diagnose the issue myself

**Comment by JitseB** [comment]
Issue #58 has been solved. I'll add your additions to the library so you can use your JDK of choice.
Hopefully I'll have an update posted by the end of the day.

**Comment by JitseB** [comment]
Solved. Will soon post a release with the fix.

**Comment by JitseB** [comment]
https://github.com/JitseB/NPCLib/releases/tag/2.4.2-SNAPSHOT
